import heroImage from "../assets/hero_section.png";
import Button from "./ui/Button.jsx";
import Icon from "./ui/Icon.jsx";
import Reveal from "./ui/Reveal.jsx";
import { Eyebrow } from "./ui/Section.jsx";

// Restates the service pillars below the fold-line — no invented metrics.
const pillars = ["Ingest", "Process", "Integrate", "Analyze", "Govern"];

export default function Hero() {
  return (
    <section className="surface-dark pb-16 pt-14 md:pb-20 md:pt-24 lg:pb-24">
      <div className="grid-lines mask-fade pointer-events-none absolute inset-0" aria-hidden="true" />

      <div className="relative z-[2] mx-auto max-w-site px-5 md:px-8">
        <div className="grid items-center gap-12 lg:grid-cols-[1fr_1.05fr] lg:gap-16">
          <div>
            <Reveal>
              <Eyebrow dark>We process data. You drive innovation.</Eyebrow>
            </Reveal>

            <Reveal delay={80}>
              <h1 className="mt-6 text-display-xl font-bold text-white">
                Turning industrial data into business{" "}
                <span className="relative text-brand-500">
                  intelligence.
                  <span
                    className="absolute -bottom-1 left-0 h-[3px] w-full bg-gradient-to-r from-brand-500 to-transparent"
                    aria-hidden="true"
                  />
                </span>
              </h1>
            </Reveal>

            <Reveal delay={160}>
              <p className="mt-7 max-w-[520px] text-[17px] leading-[1.65] text-slate-300">
                We collect, process and transform data generated by machines, robots and industrial systems into clean,
                reliable insights that power better decisions.
              </p>
            </Reveal>

            <Reveal delay={240} className="mt-10 flex flex-wrap gap-4">
              <Button href="#solutions" variant="primary">
                Explore our solutions
              </Button>
              <Button href="#contact" variant="outlineDark" icon={null}>
                Talk to our data experts
              </Button>
            </Reveal>

            <Reveal delay={320} className="mt-12 border-t border-white/10 pt-7">
              <div className="mb-4 font-mono text-[11px] uppercase tracking-[0.18em] text-slate-500">
                The full data lifecycle
              </div>
              <ul className="flex flex-wrap items-center gap-x-3 gap-y-2.5">
                {pillars.map((pillar, index) => (
                  <li key={pillar} className="flex items-center gap-3">
                    <span className="text-[13.5px] font-semibold text-slate-200">{pillar}</span>
                    {index < pillars.length - 1 && (
                      <span className="h-1 w-1 rounded-full bg-brand-500/70" aria-hidden="true" />
                    )}
                  </li>
                ))}
              </ul>
            </Reveal>
          </div>

          <Reveal delay={120} className="relative">
            {/* Ambient glow anchoring the product visual */}
            <div
              className="pointer-events-none absolute left-1/2 top-1/2 h-[78%] w-[86%] -translate-x-1/2 -translate-y-1/2 rounded-full bg-data-500/20 blur-[90px]"
              aria-hidden="true"
            />
            <div className="relative flex h-[300px] items-center justify-center sm:h-[400px] lg:h-[560px]">
              <img
                src={heroImage}
                alt="Industrial dashboard showing throughput, quality score and event volume alongside a robotic assembly cell"
                className="h-full w-full object-contain drop-shadow-[0_24px_48px_rgba(0,0,0,0.45)]"
                loading="eager"
                fetchPriority="high"
              />
            </div>

            {/* Live-status chip — reinforces the real-time positioning */}
            <div className="absolute bottom-2 left-2 hidden items-center gap-2.5 border border-white/12 bg-navy-950/80 px-4 py-2.5 backdrop-blur-sm sm:inline-flex">
              <span className="relative flex h-2 w-2">
                <span className="absolute inline-flex h-full w-full animate-pulse-dot rounded-full bg-brand-500" />
                <span className="relative inline-flex h-2 w-2 rounded-full bg-brand-500" />
              </span>
              <span className="font-mono text-[11px] uppercase tracking-[0.14em] text-slate-300">
                Real-time pipelines
              </span>
            </div>
          </Reveal>
        </div>
      </div>

      {/* Scroll affordance */}
      <div className="relative z-[2] mx-auto mt-12 hidden max-w-site px-5 md:px-8 lg:block">
        <a
          href="#what-we-do"
          className="inline-flex items-center gap-2 font-mono text-[11px] uppercase tracking-[0.18em] text-slate-400 transition-colors duration-200 hover:text-brand-500"
        >
          <Icon name="arrowRight" className="h-4 w-4 rotate-90" />
          Scroll to explore
        </a>
      </div>
    </section>
  );
}
